"""
Supabase Integration Service
Handles automated PostgreSQL schema generation, data transformation, and batched REST synchronization.
"""
import os
import re
import logging
from typing import Dict, Any, List, Optional, Tuple
import httpx
import numpy as np
import pandas as pd

from services.dataset_store import dataset_store

logger = logging.getLogger("supabase_service")


class SupabaseService:
    """Service for connecting and pushing datasets to Supabase PostgreSQL instances."""

    @staticmethod
    def get_default_credentials() -> Dict[str, Any]:
        """Fetch pre-configured Supabase credentials from backend environment variables."""
        url = (os.getenv("SUPABASE_URL") or os.getenv("NEXT_PUBLIC_SUPABASE_URL") or "").strip()
        service_key = (os.getenv("SUPABASE_SERVICE_ROLE_KEY") or "").strip()
        pub_key = (os.getenv("SUPABASE_KEY") or os.getenv("NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY") or "").strip()
        active_key = service_key or pub_key
        has_creds = bool(url and active_key)
        return {
            "supabase_url": url,
            "publishable_key": pub_key,
            "has_credentials": has_creds,
            "is_configured": bool(has_creds and "supabase.co" in url),
            "key_type": "service_role" if service_key else ("publishable" if pub_key else "none"),
            "masked_key": f"{active_key[:8]}...{active_key[-6:]}" if len(active_key) > 16 else ("***" if active_key else "")
        }

    @staticmethod
    def sanitize_column_name(col: str) -> str:
        """Converts arbitrary column names to safe PostgreSQL identifiers."""
        # Replace non-alphanumeric with underscores
        clean = re.sub(r'[^a-zA-Z0-9_]', '_', str(col).strip().lower())
        clean = re.sub(r'_+', '_', clean).strip('_')
        # Identifiers cannot begin with a number
        if clean and clean[0].isdigit():
            clean = f"col_{clean}"
        return clean or "column_val"

    @classmethod
    def map_dtype_to_postgres(cls, dtype: Any) -> str:
        """Maps pandas data types to valid PostgreSQL data types."""
        dtype_str = str(dtype).lower()
        if "int" in dtype_str:
            return "BIGINT"
        elif "float" in dtype_str or "decimal" in dtype_str or "numeric" in dtype_str:
            return "DOUBLE PRECISION"
        elif "bool" in dtype_str:
            return "BOOLEAN"
        elif "datetime" in dtype_str or "timestamp" in dtype_str:
            return "TIMESTAMPTZ"
        else:
            return "TEXT"

    @classmethod
    def generate_sql_schema(cls, df: pd.DataFrame, table_name: str) -> str:
        """Generates a complete PostgreSQL CREATE TABLE SQL script with normalized columns."""
        clean_table = cls.sanitize_column_name(table_name) or "clarion_dataset"
        columns_sql = ["    id BIGSERIAL PRIMARY KEY", "    _synced_at TIMESTAMPTZ DEFAULT NOW()"]

        for col in df.columns:
            clean_col = cls.sanitize_column_name(col)
            pg_type = cls.map_dtype_to_postgres(df[col].dtype)
            columns_sql.append(f"    {clean_col} {pg_type}")

        cols_body = ",\n".join(columns_sql)
        sql = (
            f"-- Generated by Clarion Data for Supabase PostgreSQL\n"
            f"CREATE TABLE IF NOT EXISTS public.{clean_table} (\n"
            f"{cols_body}\n"
            f");\n\n"
            f"-- Optional: Enable Row Level Security (RLS) or grant public access for development\n"
            f"ALTER TABLE public.{clean_table} ENABLE ROW LEVEL SECURITY;\n"
            f"CREATE POLICY IF NOT EXISTS \"Allow all operations for anon/authenticated\"\n"
            f"ON public.{clean_table} FOR ALL USING (true) WITH CHECK (true);\n"
        )
        return sql

    @classmethod
    def prepare_dataframe_records(cls, df: pd.DataFrame) -> Tuple[List[Dict[str, Any]], Dict[str, str]]:
        """Cleans and formats records for JSON ingestion by Supabase PostgREST API."""
        column_mapping = {}
        for col in df.columns:
            column_mapping[col] = cls.sanitize_column_name(col)

        # Work on a copy with sanitized column names
        renamed_df = df.rename(columns=column_mapping)

        records = renamed_df.to_dict(orient="records")
        for row in records:
            for k, v in row.items():
                if pd.isna(v) or v is np.nan or v == float("inf") or v == float("-inf"):
                    row[k] = None
                elif isinstance(v, (pd.Timestamp, np.datetime64)):
                    row[k] = str(v)

        return records, column_mapping

    @classmethod
    async def test_connection(
        cls,
        supabase_url: Optional[str] = None,
        supabase_key: Optional[str] = None
    ) -> Dict[str, Any]:
        """Verifies if the provided or pre-configured backend Supabase URL and API Key are reachable and valid."""
        env_creds = cls.get_default_credentials()
        clean_url = (supabase_url if supabase_url is not None else env_creds.get("supabase_url", "")).strip().rstrip('/')
        default_key = os.getenv("SUPABASE_SERVICE_ROLE_KEY", "") or os.getenv("SUPABASE_KEY", "") or os.getenv("NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY", "")
        clean_key = (supabase_key if supabase_key is not None else default_key).strip()

        if not clean_url or not clean_key:
            return {"valid": False, "message": "Supabase Project URL and API Key are required."}

        if not clean_url.startswith("http://") and not clean_url.startswith("https://"):
            clean_url = f"https://{clean_url}"

        # PostgREST root API verification
        test_url = f"{clean_url}/rest/v1/"
        headers = {
            "apikey": clean_key,
            "Authorization": f"Bearer {clean_key}"
        }

        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                res = await client.get(test_url, headers=headers)
                # PostgREST returns 200 or OpenAPI schema if valid
                if res.status_code in [200, 204]:
                    return {
                        "valid": True,
                        "status_code": res.status_code,
                        "message": "Successfully authenticated with Supabase Project!"
                    }
                elif res.status_code in [401, 403]:
                    return {
                        "valid": False,
                        "status_code": res.status_code,
                        "message": "Authentication failed: Invalid Supabase API key."
                    }
                else:
                    return {
                        "valid": False,
                        "status_code": res.status_code,
                        "message": f"Supabase responded with status {res.status_code}: {res.text[:150]}"
                    }
        except httpx.RequestError as exc:
            return {
                "valid": False,
                "message": f"Connection error reaching Supabase endpoint: {str(exc)}"
            }

    @classmethod
    async def push_dataset(
        cls,
        dataset_id: str,
        table_name: Optional[str] = None,
        supabase_url: Optional[str] = None,
        supabase_key: Optional[str] = None,
        use_cleaned: bool = True,
        batch_size: int = 500
    ) -> Dict[str, Any]:
        """
        Pushes all records from active dataset to a Supabase PostgreSQL table in streaming batches.
        """
        # Resolve Credentials
        env_creds = cls.get_default_credentials()
        url = (supabase_url or env_creds["supabase_url"] or "").strip().rstrip('/')
        key = (supabase_key or os.getenv("SUPABASE_SERVICE_ROLE_KEY", "") or os.getenv("SUPABASE_KEY", "") or os.getenv("NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY", "") or "").strip()

        if not url or not key:
            raise ValueError("Supabase Project URL and API Key are required to synchronize data.")

        if not url.startswith("http://") and not url.startswith("https://"):
            url = f"https://{url}"

        # Fetch Dataset DataFrame
        df = None
        if use_cleaned:
            try:
                from app.services.cleaning_service import CleaningService
                clean_res = CleaningService.get_cleaned_dataset(dataset_id)
                if clean_res and "cleaned_df" in clean_res and isinstance(clean_res["cleaned_df"], pd.DataFrame):
                    df = clean_res["cleaned_df"]
            except Exception as e:
                logger.debug(f"Falling back to stored dataset: {e}")

        if df is None:
            df = dataset_store.get_dataset(dataset_id)

        if df is None:
            raise ValueError(f"Dataset '{dataset_id}' not found in memory or disk store.")

        # Resolve Target Table Name
        if not table_name or not table_name.strip():
            meta = dataset_store.get_metadata(dataset_id) or {}
            base_name = meta.get("name", dataset_id).replace('.csv', '').replace('.xlsx', '')
            table_name = f"clarion_{cls.sanitize_column_name(base_name)}"
        else:
            table_name = cls.sanitize_column_name(table_name)

        # Generate SQL Schema for User Reference
        sql_schema = cls.generate_sql_schema(df, table_name)

        # Prepare Records
        records, col_mapping = cls.prepare_dataframe_records(df)
        total_records = len(records)

        if total_records == 0:
            return {
                "status": "success",
                "rows_pushed": 0,
                "table_name": table_name,
                "message": "Dataset contains 0 rows. No records pushed.",
                "sql_schema": sql_schema
            }

        # Batched REST insertion into Supabase
        target_endpoint = f"{url}/rest/v1/{table_name}"
        headers = {
            "apikey": key,
            "Authorization": f"Bearer {key}",
            "Content-Type": "application/json",
            "Prefer": "return=minimal"
        }

        pushed_count = 0
        batches = [records[i:i + batch_size] for i in range(0, total_records, batch_size)]

        async with httpx.AsyncClient(timeout=30.0) as client:
            for idx, batch in enumerate(batches):
                try:
                    res = await client.post(target_endpoint, headers=headers, json=batch)
                    
                    # 201 Created or 200 OK
                    if res.status_code in [200, 201, 204]:
                        pushed_count += len(batch)
                    elif res.status_code == 404:
                        error_detail = res.text
                        msg = (
                            f"Target table '{table_name}' does not exist in your Supabase database yet. "
                            f"Please run the generated SQL query in your Supabase SQL Editor to create it."
                        )
                        return {
                            "status": "table_missing",
                            "table_name": table_name,
                            "rows_pushed": pushed_count,
                            "total_rows": total_records,
                            "error": msg,
                            "supabase_detail": error_detail,
                            "sql_schema": sql_schema
                        }
                    else:
                        return {
                            "status": "error",
                            "table_name": table_name,
                            "rows_pushed": pushed_count,
                            "total_rows": total_records,
                            "error": f"Supabase API returned error HTTP {res.status_code}: {res.text}",
                            "sql_schema": sql_schema
                        }
                except Exception as exc:
                    return {
                        "status": "error",
                        "table_name": table_name,
                        "rows_pushed": pushed_count,
                        "total_rows": total_records,
                        "error": f"Failed while pushing batch {idx + 1} of {len(batches)}: {str(exc)}",
                        "sql_schema": sql_schema
                    }

        return {
            "status": "success",
            "table_name": table_name,
            "rows_pushed": pushed_count,
            "total_rows": total_records,
            "batches": len(batches),
            "sql_schema": sql_schema,
            "message": f"Successfully pushed {pushed_count:,} records into Supabase table '{table_name}'!"
        }
